# Generated by Django 4.1 on 2022-09-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('search_term', models.CharField(blank=True, max_length=255, null=True)),
                ('article_body', models.TextField(blank=True, null=True)),
                ('reading_count', models.IntegerField(max_length=255, default='0')),
            ],
            options={
                'db_table': 'scraped_data_tbl',
            },
        ),
    ]
